name: Build
description: Build apache image
inputs:
  version:
    description: version
    required: true
  tags:
    description: image tags
    required: true
  platform:
    description: docker platform
    required: false
    default: linux/amd64
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      APACHE_VER: ${{ inputs.version }}
      TAGS: ${{ inputs.tags }}
      PLATFORM: ${{ inputs.platform }}
    # First build for single-arch for tests (--load flag doesn't work for multiple platforms).
    run: |
      set -e
      PLATFORM=linux/amd64 make buildx-build
      make test
      make buildx-build
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
