name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

jobs:
  apache-24:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 2.4.46
        tags: 2.4,2,latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
